AppName: "Business Directory"

URLPrefix: "directory"

Host: "localhost"

Port: "8000"

AllowedOrigin:
  - "http://localhost:8000"
  - "http://localhost:4001"

TrustedProxies:
  - "192.168.1.2"

DEBUG: true

MongoDBName: "directory"

