AppName: "Business Directory"

Host: "localhost"

Port: "8000"
AesKey: "thisis32bitlongpassphraseimusing"

AllowedOrigin:
  - "http://localhost:3000"
  - "http://localhost:4001"

TrustedProxies:
  - "192.168.1.2"

DEBUG: true

MongoURI: "mongodb://localhost:27017"

MongoDBName: "Directory"

ClientCollection: "Clients"