// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package model

type DeleteUser struct {
	Index int `json:"index"`
}

type GetUser struct {
	ID int `json:"id"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
