basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: tech.builder.cirle@gmail.com
    name: Techbuilder Support
  description: This is the API for business directory api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Business directory API
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
