basePath: /directory/api/v1
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API for business directory api..
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Business directory API
  version: "1.0"
paths: {}
security:
- ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    type: basic
swagger: "2.0"
